# [veterinerdb]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [veterinerdb]    Script Date: 29.12.2023 22:47:45 ******/
CREATE DATABASE [veterinerdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'veterinerdb', FILENAME = N'D:\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\veterinerdb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'veterinerdb_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\veterinerdb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [veterinerdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [veterinerdb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [veterinerdb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [veterinerdb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [veterinerdb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [veterinerdb] SET ARITHABORT OFF 
GO
ALTER DATABASE [veterinerdb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [veterinerdb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [veterinerdb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [veterinerdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [veterinerdb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [veterinerdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [veterinerdb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [veterinerdb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [veterinerdb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [veterinerdb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [veterinerdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [veterinerdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [veterinerdb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [veterinerdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [veterinerdb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [veterinerdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [veterinerdb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [veterinerdb] SET RECOVERY FULL 
GO
ALTER DATABASE [veterinerdb] SET  MULTI_USER 
GO
ALTER DATABASE [veterinerdb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [veterinerdb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [veterinerdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [veterinerdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [veterinerdb] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'veterinerdb', N'ON'
GO

# [dbo].[Asi_Test_Bilgileri]

In [0]:
USE [veterinerdb]
GO

In [0]:
/****** Object:  Table [dbo].[Asi_Test_Bilgileri]    Script Date: 29.12.2023 22:47:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Asi_Test_Bilgileri](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[hastaId] [int] NOT NULL,
	[testTur] [varchar](50) NULL,
	[testSonuc] [varchar](50) NULL,
	[AsiDozaj] [float] NULL,
	[AsiTur] [varchar](50) NULL,
	[Tarih] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[hasta_bilgi]

In [0]:
/****** Object:  Table [dbo].[hasta_bilgi]    Script Date: 29.12.2023 22:47:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[hasta_bilgi](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[sahipId] [int] NOT NULL,
	[veterinerId] [int] NOT NULL,
	[tur] [varchar](30) NOT NULL,
	[cins] [varchar](30) NOT NULL,
	[ad] [varchar](30) NOT NULL,
	[sonGelmeTarihi] [date] NULL,
	[yas] [int] NOT NULL,
	[agirlik] [float] NOT NULL,
	[kisirlikDurumu] [varchar](1) NOT NULL,
	[cipDurumu] [varchar](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[hastalik_gecmisi]

In [0]:
/****** Object:  Table [dbo].[hastalik_gecmisi]    Script Date: 29.12.2023 22:47:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[hastalik_gecmisi](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[hastaId] [int] NOT NULL,
	[hastalikAd] [varchar](120) NOT NULL,
	[durum] [varchar](30) NOT NULL,
	[tehsisTarihi] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[hizmet_bilgi]

In [0]:
/****** Object:  Table [dbo].[hizmet_bilgi]    Script Date: 29.12.2023 22:47:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[hizmet_bilgi](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[hastaId] [int] NOT NULL,
	[hizmetAd] [varchar](30) NOT NULL,
	[hizmetTarih] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[kategori]

In [0]:
/****** Object:  Table [dbo].[kategori]    Script Date: 29.12.2023 22:47:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[kategori](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[kategoriAd] [varchar](120) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[klinik_bilgi]

In [0]:
/****** Object:  Table [dbo].[klinik_bilgi]    Script Date: 29.12.2023 22:47:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[klinik_bilgi](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[klinikAd] [varchar](30) NOT NULL,
	[konumu] [varchar](120) NOT NULL,
	[bolge] [varchar](60) NOT NULL,
	[mail] [varchar](60) NOT NULL,
	[telNo] [varchar](11) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[musteri_faturalari]

In [0]:
/****** Object:  Table [dbo].[musteri_faturalari]    Script Date: 29.12.2023 22:47:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[musteri_faturalari](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[musteriId] [int] NOT NULL,
	[faturaDetay] [varchar](30) NOT NULL,
	[tutar] [float] NOT NULL,
	[odemeTuru] [varchar](20) NULL,
	[kesimTarihi] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[personel_bilgi]

In [0]:
/****** Object:  Table [dbo].[personel_bilgi]    Script Date: 29.12.2023 22:47:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[personel_bilgi](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[klinikId] [int] NOT NULL,
	[ad] [varchar](20) NOT NULL,
	[soyad] [varchar](20) NOT NULL,
	[dogumTarihi] [date] NULL,
	[unvan] [varchar](50) NOT NULL,
	[maas] [int] NOT NULL,
	[girisTarihi] [date] NOT NULL,
	[mail] [varchar](60) NULL,
	[telNo] [varchar](11) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[rel_urun]

In [0]:
/****** Object:  Table [dbo].[rel_urun]    Script Date: 29.12.2023 22:47:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[rel_urun](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[klinikId] [int] NOT NULL,
	[urunId] [int] NOT NULL,
	[urunAdet] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[sahip_bilgi]

In [0]:
/****** Object:  Table [dbo].[sahip_bilgi]    Script Date: 29.12.2023 22:47:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[sahip_bilgi](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[ad] [varchar](20) NOT NULL,
	[soyad] [varchar](20) NOT NULL,
	[evAdresi] [varchar](120) NOT NULL,
	[mail] [varchar](60) NULL,
	[telNo] [varchar](11) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[tedarikci_bilgi]

In [0]:
/****** Object:  Table [dbo].[tedarikci_bilgi]    Script Date: 29.12.2023 22:47:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tedarikci_bilgi](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[ad] [varchar](60) NOT NULL,
	[konum] [varchar](160) NOT NULL,
	[mail] [varchar](60) NULL,
	[telNo] [varchar](11) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[urun_bilgi]

In [0]:
/****** Object:  Table [dbo].[urun_bilgi]    Script Date: 29.12.2023 22:47:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[urun_bilgi](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[kategoriId] [int] NOT NULL,
	[tedarikId] [int] NOT NULL,
	[UrunAd] [varchar](120) NOT NULL,
	[urunFiyat] [float] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[urun_fatura_bilgi]

In [0]:
/****** Object:  Table [dbo].[urun_fatura_bilgi]    Script Date: 29.12.2023 22:47:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[urun_fatura_bilgi](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[urunId] [int] NOT NULL,
	[ad] [varchar](60) NOT NULL,
	[soyad] [varchar](60) NOT NULL,
	[tutar] [float] NOT NULL,
	[odemeTuru] [varchar](20) NULL,
	[topAdet] [int] NOT NULL,
	[kesimTarihi] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Asi_Test_Bilgileri]

In [0]:
SET IDENTITY_INSERT [dbo].[Asi_Test_Bilgileri] ON 
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (1, 1, N'Kan Testi', N'Normal', 0.3, N'Kuduz Aşısı', CAST(N'2023-01-01' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (2, 1, N'Parazit Testi', N'Pozitif', NULL, NULL, CAST(N'2023-01-05' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (3, 2, N'Kan Testi', N'Yüksek', 0.6, N'Köpek Distemper Aşısı', CAST(N'2023-02-10' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (4, 2, N'Parazit Testi', N'Negatif', NULL, NULL, CAST(N'2023-02-15' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (5, 3, N'Kan Testi', N'Normal', 0.4, N'Kedi Panleukopenia Aşısı', CAST(N'2023-03-20' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (6, 3, N'Parazit Testi', N'Negatif', NULL, NULL, CAST(N'2023-03-25' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (7, 4, N'Kan Testi', N'Yüksek', 0.1, N'Köpek Parvovirus Aşısı', CAST(N'2023-04-05' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (8, 4, N'Parazit Testi', N'Pozitif', NULL, NULL, CAST(N'2023-04-10' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (9, 5, N'Kan Testi', N'Normal', 0.7, N'Köpek Leptospirosis Aşısı', CAST(N'2023-05-15' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (10, 5, N'Parazit Testi', N'Negatif', NULL, NULL, CAST(N'2023-05-20' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (11, 6, N'Kan Testi', N'Yüksek', 0.4, N'Kuduz Aşısı', CAST(N'2023-06-01' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (12, 6, N'Parazit Testi', N'Pozitif', NULL, NULL, CAST(N'2023-06-05' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (13, 7, N'Kan Testi', N'Normal', 0.3, N'Köpek Distemper Aşısı', CAST(N'2023-07-10' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (14, 7, N'Parazit Testi', N'Negatif', NULL, NULL, CAST(N'2023-07-15' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (15, 8, N'Kan Testi', N'Yüksek', 0.7, N'Kedi Panleukopenia Aşısı', CAST(N'2023-08-20' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (16, 8, N'Parazit Testi', N'Negatif', NULL, NULL, CAST(N'2023-08-25' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (17, 9, N'Kan Testi', N'Normal', 0.4, N'Köpek Parvovirus Aşısı', CAST(N'2023-09-30' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (18, 9, N'Parazit Testi', N'Pozitif', NULL, NULL, CAST(N'2023-10-05' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (19, 10, N'Kan Testi', N'Yüksek', 0.3, N'Köpek Leptospirosis Aşısı', CAST(N'2023-11-10' AS Date))
INSERT [dbo].[Asi_Test_Bilgileri] ([id], [hastaId], [testTur], [testSonuc], [AsiDozaj], [AsiTur], [Tarih]) VALUES (20, 10, N'Parazit Testi', N'Pozitif', NULL, NULL, CAST(N'2023-11-15' AS Date))
SET IDENTITY_INSERT [dbo].[Asi_Test_Bilgileri] OFF
GO

# [dbo].[hasta_bilgi]

In [0]:
SET IDENTITY_INSERT [dbo].[hasta_bilgi] ON 
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (1, 1, 5, N'Köpek', N'Golden Retriever', N'Max', CAST(N'2021-06-15' AS Date), 3, 5.8, N'H', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (2, 2, 14, N'Kedi', N'Scottish Fold', N'Luna', CAST(N'2021-04-20' AS Date), 1, 2.7, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (3, 3, 14, N'Köpek', N'Labrador Retriever', N'Bella', CAST(N'2021-07-05' AS Date), 2, 4.1, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (4, 4, 14, N'Kedi', N'British Shorthair', N'Charlie', CAST(N'2021-08-10' AS Date), 3, 3.5, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (5, 5, 3, N'Köpek', N'German Shepherd', N'Rocky', CAST(N'2021-09-15' AS Date), 4, 6.9, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (6, 6, 3, N'Kedi', N'Persian', N'Lucy', CAST(N'2021-03-20' AS Date), 2, 2.7, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (7, 6, 3, N'Köpek', N'French Bulldog', N'Cooper', CAST(N'2021-10-05' AS Date), 1, 3.2, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (8, 7, 3, N'Kedi', N'Siamese', N'Oliver', CAST(N'2021-11-10' AS Date), 3, 4.4, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (9, 8, 8, N'Köpek', N'Poodle', N'Milo', CAST(N'2021-12-15' AS Date), 2, 5.8, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (10, 9, 8, N'Kedi', N'Maine Coon', N'Simba', CAST(N'2022-01-20' AS Date), 2, 4.6, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (11, 10, 8, N'Köpek', N'Bulldog', N'Maximus', CAST(N'2022-02-05' AS Date), 3, 7.2, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (12, 10, 9, N'Kedi', N'Ragdoll', N'Lily', CAST(N'2022-03-10' AS Date), 1, 3.3, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (13, 11, 9, N'Köpek', N'Siberian Husky', N'Luna', CAST(N'2022-04-15' AS Date), 2, 5.5, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (14, 12, 7, N'Kedi', N'Sphynx', N'Milo', CAST(N'2022-05-20' AS Date), 3, 2.9, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (15, 13, 7, N'Köpek', N'Rottweiler', N'Rocko', CAST(N'2022-06-05' AS Date), 4, 8.1, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (16, 14, 12, N'Kedi', N'Bengal', N'Leo', CAST(N'2022-07-10' AS Date), 2, 3.8, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (17, 15, 12, N'Köpek', N'Chihuahua', N'Bella', CAST(N'2022-08-15' AS Date), 1, 2.5, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (18, 15, 12, N'Kedi', N'Norwegian Forest', N'Mia', CAST(N'2022-09-20' AS Date), 3, 4.1, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (19, 16, 12, N'Köpek', N'Boxer', N'Max', CAST(N'2022-10-05' AS Date), 2, 6.3, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (20, 17, 13, N'Kedi', N'Persian', N'Milo', CAST(N'2022-11-10' AS Date), 2, 3.4, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (21, 18, 13, N'Köpek', N'Labrador Retriever', N'Charlie', CAST(N'2022-12-15' AS Date), 3, 5.9, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (22, 19, 13, N'Kedi', N'Siamese', N'Oliver', CAST(N'2023-01-20' AS Date), 1, 4.2, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (23, 20, 11, N'Köpek', N'Golden Retriever', N'Maximus', CAST(N'2023-02-05' AS Date), 2, 7.5, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (24, 21, 11, N'Kedi', N'Scottish Fold', N'Luna', CAST(N'2023-03-10' AS Date), 3, 3.1, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (25, 22, 11, N'Köpek', N'German Shepherd', N'Rocky', CAST(N'2023-04-15' AS Date), 4, 6.5, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (26, 23, 19, N'Kedi', N'British Shorthair', N'Lucy', CAST(N'2023-05-20' AS Date), 2, 2.9, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (27, 23, 19, N'Köpek', N'French Bulldog', N'Cooper', CAST(N'2023-06-05' AS Date), 1, 3.6, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (28, 23, 19, N'Kedi', N'Maine Coon', N'Oliver', CAST(N'2023-07-10' AS Date), 3, 4.8, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (29, 24, 4, N'Köpek', N'Poodle', N'Milo', CAST(N'2023-08-15' AS Date), 2, 5.3, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (30, 25, 4, N'Kedi', N'Ragdoll', N'Lily', CAST(N'2023-09-20' AS Date), 1, 3.7, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (31, 26, 4, N'Köpek', N'Siberian Husky', N'Luna', CAST(N'2023-10-05' AS Date), 2, 5.2, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (32, 26, 18, N'Kedi', N'Sphynx', N'Milo', CAST(N'2023-11-10' AS Date), 3, 2.8, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (33, 27, 18, N'Köpek', N'Rottweiler', N'Rocko', CAST(N'2023-12-15' AS Date), 4, 8.3, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (34, 28, 18, N'Kedi', N'Bengal', N'Leo', CAST(N'2023-01-20' AS Date), 2, 3.5, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (35, 29, 20, N'Köpek', N'Chihuahua', N'Bella', CAST(N'2023-02-05' AS Date), 1, 2.7, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (36, 29, 20, N'Kedi', N'Norwegian Forest', N'Mia', CAST(N'2023-03-10' AS Date), 3, 4.4, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (37, 29, 17, N'Köpek', N'Boxer', N'Max', CAST(N'2023-04-15' AS Date), 2, 6.1, N'E', N'E')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (38, 30, 17, N'Kedi', N'Persian', N'Milo', CAST(N'2023-05-20' AS Date), 2, 3.2, N'H', N'H')
INSERT [dbo].[hasta_bilgi] ([id], [sahipId], [veterinerId], [tur], [cins], [ad], [sonGelmeTarihi], [yas], [agirlik], [kisirlikDurumu], [cipDurumu]) VALUES (39, 30, 17, N'Köpek', N'Labrador Retriever', N'Charlie', CAST(N'2023-06-05' AS Date), 3, 5.7, N'E', N'E')
SET IDENTITY_INSERT [dbo].[hasta_bilgi] OFF
GO

# [dbo].[hastalik_gecmisi]

In [0]:
SET IDENTITY_INSERT [dbo].[hastalik_gecmisi] ON 
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (1, 1, N'İshal', N'Kontrol Altında', CAST(N'2021-05-10' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (2, 2, N'Kulak Enfeksiyonu', N'Stabil', CAST(N'2021-06-15' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (3, 8, N'Alerji', N'Stabil', CAST(N'2021-07-20' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (4, 6, N'Göz Enfeksiyonu', N'Kontrol Altında', CAST(N'2021-08-05' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (5, 5, N'Solunum Problemi', N'Kontrol Altında', CAST(N'2021-09-10' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (6, 6, N'Yara İyileşmesi', N'Kontrol Altında', CAST(N'2021-10-15' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (7, 7, N'Kemik Kırığı', N'Kontrol Altında', CAST(N'2021-11-20' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (8, 23, N'Karaciğer Problemi', N'Stabil', CAST(N'2021-12-25' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (9, 4, N'Böbrek İltihabı', N'Kontrol Altında', CAST(N'2022-01-30' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (10, 10, N'Kalp Rahatsızlığı', N'Kritik', CAST(N'2022-02-05' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (11, 11, N'Mide Ülseri', N'Kontrol Altında', CAST(N'2022-03-10' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (12, 11, N'Kemik İltihabı', N'Kontrol Altında', CAST(N'2022-04-15' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (13, 13, N'Kulak Enfeksiyonu', N'Kontrol Altında', CAST(N'2022-05-20' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (14, 14, N'Alerji', N'Stabil', CAST(N'2022-06-25' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (15, 15, N'Göz Enfeksiyonu', N'Kontrol Altında', CAST(N'2022-07-30' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (16, 16, N'Solunum Problemi', N'Kritik', CAST(N'2022-08-05' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (17, 19, N'Yara İyileşmesi', N'Kontrol Altında', CAST(N'2022-09-10' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (18, 18, N'Kemik Kırığı', N'Kontrol Altında', CAST(N'2022-10-15' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (19, 19, N'Karaciğer Problemi', N'Stabil', CAST(N'2022-11-20' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (20, 20, N'Böbrek İltihabı', N'Kontrol Altında', CAST(N'2022-12-25' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (21, 21, N'Kalp Rahatsızlığı', N'Kontrol Altında', CAST(N'2023-01-30' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (22, 22, N'Mide Ülseri', N'Kontrol Altında', CAST(N'2023-02-05' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (23, 23, N'Kemik İltihabı', N'Kritik', CAST(N'2023-03-10' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (24, 24, N'Kulak Enfeksiyonu', N'Kontrol Altında', CAST(N'2023-04-15' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (25, 25, N'Alerji', N'Kontrol Altında', CAST(N'2023-05-20' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (26, 26, N'Göz Enfeksiyonu', N'Stabil', CAST(N'2023-06-25' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (27, 27, N'Solunum Problemi', N'Kontrol Altında', CAST(N'2023-07-30' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (28, 28, N'Yara İyileşmesi', N'Stabil', CAST(N'2023-08-05' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (29, 29, N'Kemik Kırığı', N'Kontrol Altında', CAST(N'2023-09-10' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (30, 29, N'Karaciğer Problemi', N'Kritik', CAST(N'2023-10-15' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (31, 6, N'Halsizlik', N'Kontrol Altında', CAST(N'2023-11-20' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (32, 2, N'Kulak Enfeksiyonu', N'Stabil', CAST(N'2023-12-25' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (33, 8, N'Alerji', N'Stabil', CAST(N'2023-01-30' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (34, 23, N'Göz Enfeksiyonu', N'Kontrol Altında', CAST(N'2023-02-05' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (35, 28, N'Solunum Problemi', N'Kontrol Altında', CAST(N'2023-03-10' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (36, 30, N'Yara İyileşmesi', N'Kontrol Altında', CAST(N'2023-04-15' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (37, 7, N'Kemik Kırığı', N'Kontrol Altında', CAST(N'2023-05-20' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (38, 23, N'Karaciğer Problemi', N'Stabil', CAST(N'2023-06-25' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (39, 4, N'Böbrek İltihabı', N'Kontrol Altında', CAST(N'2023-07-30' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (40, 10, N'Kalp Rahatsızlığı', N'Kritik', CAST(N'2023-08-05' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (41, 11, N'Mide Ülseri', N'Kontrol Altında', CAST(N'2023-09-10' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (42, 11, N'Kemik İltihabı', N'Kontrol Altında', CAST(N'2023-10-15' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (43, 13, N'Kulak Enfeksiyonu', N'Kontrol Altında', CAST(N'2023-11-20' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (44, 14, N'Alerji', N'Stabil', CAST(N'2023-12-25' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (45, 15, N'Göz Enfeksiyonu', N'Kontrol Altında', CAST(N'2023-01-30' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (46, 16, N'Solunum Problemi', N'Kritik', CAST(N'2023-02-05' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (47, 19, N'Yara İyileşmesi', N'Kontrol Altında', CAST(N'2023-03-10' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (48, 25, N'Kemik Kırığı', N'Kontrol Altında', CAST(N'2023-04-15' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (49, 19, N'Karaciğer Problemi', N'Stabil', CAST(N'2023-05-20' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (50, 20, N'Böbrek İltihabı', N'Kontrol Altında', CAST(N'2023-06-25' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (51, 30, N'Kalp Rahatsızlığı', N'Kontrol Altında', CAST(N'2023-07-30' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (52, 26, N'Mide Ülseri', N'Kontrol Altında', CAST(N'2023-08-05' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (53, 23, N'Kemik İltihabı', N'Kritik', CAST(N'2023-09-10' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (54, 24, N'Kulak Enfeksiyonu', N'Kontrol Altında', CAST(N'2023-10-15' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (55, 30, N'Alerji', N'Kontrol Altında', CAST(N'2023-11-20' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (56, 22, N'Göz Enfeksiyonu', N'Stabil', CAST(N'2023-12-25' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (57, 30, N'Solunum Problemi', N'Kontrol Altında', CAST(N'2023-01-30' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (58, 28, N'Yara İyileşmesi', N'Stabil', CAST(N'2023-02-05' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (59, 29, N'Kemik Kırığı', N'Kontrol Altında', CAST(N'2023-03-10' AS Date))
INSERT [dbo].[hastalik_gecmisi] ([id], [hastaId], [hastalikAd], [durum], [tehsisTarihi]) VALUES (60, 27, N'Karaciğer Problemi', N'Kritik', CAST(N'2023-04-15' AS Date))
SET IDENTITY_INSERT [dbo].[hastalik_gecmisi] OFF
GO

# [dbo].[hizmet_bilgi]

In [0]:
SET IDENTITY_INSERT [dbo].[hizmet_bilgi] ON 
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (1, 34, N'Muayene ve Teşhis', CAST(N'2023-08-12' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (2, 12, N'Cerrahi Müdahaleler', CAST(N'2023-03-25' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (3, 3, N'Laboratuvar Testleri', CAST(N'2023-11-08' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (4, 26, N'Hasta Bakımı ve Tedavi', CAST(N'2023-06-17' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (5, 29, N'Diş Bakımı', CAST(N'2023-02-04' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (6, 7, N'Dermatoloji Hizmetleri', CAST(N'2023-09-30' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (7, 23, N'Ultrason', CAST(N'2023-05-21' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (8, 19, N'Yara Bakımı', CAST(N'2023-12-11' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (9, 14, N'İç Hastalıklar', CAST(N'2023-07-02' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (10, 6, N'Beslenme Danışmanlığı', CAST(N'2023-01-19' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (11, 8, N'Aşılar ve Bağışıklama', CAST(N'2023-10-14' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (12, 17, N'Davranış Danışmanlığı', CAST(N'2023-04-07' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (13, 32, N'Aşılar ve Bağışıklama', CAST(N'2023-11-26' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (14, 9, N'Kanser Tedavisi', CAST(N'2023-06-09' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (15, 38, N'Anestezi ve Ağrı Kontrolü', CAST(N'2023-02-22' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (16, 5, N'Beslenme Danışmanlığı', CAST(N'2023-09-15' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (17, 36, N'Anestezi ve Ağrı Kontrolü', CAST(N'2023-05-05' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (18, 22, N'Göz Sağlığı Hizmetleri', CAST(N'2023-12-27' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (19, 29, N'Beslenme Danışmanlığı', CAST(N'2023-07-08' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (20, 20, N'Alerji Testleri', CAST(N'2023-01-31' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (21, 1, N'Röntgen ve Görüntüleme', CAST(N'2023-10-23' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (22, 11, N'Ağrı Yönetimi', CAST(N'2023-04-15' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (23, 4, N'Ortopedik Cerrahi', CAST(N'2023-11-04' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (24, 39, N'Davranış Danışmanlığı', CAST(N'2023-06-28' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (25, 30, N'Beslenme Danışmanlığı', CAST(N'2023-03-09' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (26, 13, N'Ortopedik Cerrahi', CAST(N'2023-08-02' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (27, 31, N'Röntgen ve Görüntüleme', CAST(N'2023-07-11' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (28, 16, N'Nöroloji Hizmetleri', CAST(N'2023-12-19' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (29, 25, N'Beslenme Danışmanlığı', CAST(N'2023-02-01' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (30, 2, N'Göz Sağlığı Hizmetleri', CAST(N'2023-09-20' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (31, 27, N'Evcil Hayvan Sağlık Eğitimi', CAST(N'2023-05-13' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (32, 18, N'Röntgen ve Görüntüleme', CAST(N'2023-01-05' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (33, 21, N'Ultrason', CAST(N'2023-10-30' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (34, 15, N'Nöroloji Hizmetleri', CAST(N'2023-04-22' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (35, 10, N'Ultrason', CAST(N'2023-04-22' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (36, 28, N'Evcil Hayvan Sağlık Eğitimi', CAST(N'2023-06-03' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (37, 35, N'Göz Sağlığı Hizmetleri', CAST(N'2023-06-03' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (38, 24, N'Kanser Tedavisi', CAST(N'2023-02-16' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (39, 37, N'Kanser Tedavisi', CAST(N'2023-09-09' AS Date))
INSERT [dbo].[hizmet_bilgi] ([id], [hastaId], [hizmetAd], [hizmetTarih]) VALUES (40, 33, N'Alerji Testleri', CAST(N'2023-07-24' AS Date))
SET IDENTITY_INSERT [dbo].[hizmet_bilgi] OFF
GO

# [dbo].[kategori]

In [0]:
SET IDENTITY_INSERT [dbo].[kategori] ON 
INSERT [dbo].[kategori] ([id], [kategoriAd]) VALUES (1, N'Veteriner İlaçları')
INSERT [dbo].[kategori] ([id], [kategoriAd]) VALUES (2, N'Mama')
INSERT [dbo].[kategori] ([id], [kategoriAd]) VALUES (3, N'Oyuncaklar')
INSERT [dbo].[kategori] ([id], [kategoriAd]) VALUES (4, N'Köpek Yatakları')
INSERT [dbo].[kategori] ([id], [kategoriAd]) VALUES (5, N'Kedi Tırmalama Tahtaları')
INSERT [dbo].[kategori] ([id], [kategoriAd]) VALUES (6, N'Şampuan')
INSERT [dbo].[kategori] ([id], [kategoriAd]) VALUES (7, N'Fırça')
INSERT [dbo].[kategori] ([id], [kategoriAd]) VALUES (8, N'Tasma ve Kayış')
INSERT [dbo].[kategori] ([id], [kategoriAd]) VALUES (9, N'Kedi Kumu ve Tuvaletleri')
INSERT [dbo].[kategori] ([id], [kategoriAd]) VALUES (10, N'Evcil Hayvan Bakım Ürünleri')
INSERT [dbo].[kategori] ([id], [kategoriAd]) VALUES (11, N'Veteriner Kitapları')
INSERT [dbo].[kategori] ([id], [kategoriAd]) VALUES (12, N'Kedi Yatakları')
INSERT [dbo].[kategori] ([id], [kategoriAd]) VALUES (13, N'Köpek Eğitim Malzemeleri')
INSERT [dbo].[kategori] ([id], [kategoriAd]) VALUES (14, N'Kedi Taşıma Çantaları')
INSERT [dbo].[kategori] ([id], [kategoriAd]) VALUES (15, N'Köpek Sağlık Kontrolleri')
SET IDENTITY_INSERT [dbo].[kategori] OFF
GO

# [dbo].[klinik_bilgi]

In [0]:
SET IDENTITY_INSERT [dbo].[klinik_bilgi] ON 
INSERT [dbo].[klinik_bilgi] ([id], [klinikAd], [konumu], [bolge], [mail], [telNo]) VALUES (1, N'AgdagVet', N'İstanbul', N'Esenyurt', N'info@agdagvet.com.tr', N'05334073133')
INSERT [dbo].[klinik_bilgi] ([id], [klinikAd], [konumu], [bolge], [mail], [telNo]) VALUES (2, N'KurtVet', N'Ankara', N'KeçiÖren', N'info@kurtVet.com.tr', N'05334077542')
INSERT [dbo].[klinik_bilgi] ([id], [klinikAd], [konumu], [bolge], [mail], [telNo]) VALUES (3, N'KayaVet', N'İzmir', N'Bornova', N'info@kayaVet.com.tr', N'05334075323')
INSERT [dbo].[klinik_bilgi] ([id], [klinikAd], [konumu], [bolge], [mail], [telNo]) VALUES (4, N'YildizVet', N'Samsun', N'Atakum', N'info@yildizvet.com.tr', N'05334073654')
INSERT [dbo].[klinik_bilgi] ([id], [klinikAd], [konumu], [bolge], [mail], [telNo]) VALUES (5, N'OzturkVet', N'Antalya', N'Konyaaltı', N'info@yildizvet.com.tr', N'05334073689')
SET IDENTITY_INSERT [dbo].[klinik_bilgi] OFF
GO

# [dbo].[personel_bilgi]

In [0]:
SET IDENTITY_INSERT [dbo].[personel_bilgi] ON 
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (1, 3, N'Çilem', N'Akay', CAST(N'1998-08-05' AS Date), N'Veteriner Hekim', 24000, CAST(N'2009-07-26' AS Date), N'akçilem@gmail.com', N'05491645134')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (2, 1, N'Erna', N'Arikan', CAST(N'1994-04-14' AS Date), N'Veteriner Cerrah', 22000, CAST(N'2015-09-06' AS Date), N'erarikan@gmail.com', N'05487695132')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (3, 4, N'Mustafa', N'Arif', CAST(N'2002-12-02' AS Date), N'Veteriner Hekim', 24000, CAST(N'2022-01-08' AS Date), N'muarif@gmail.com', N'05761243657')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (4, 1, N'Ali', N'Balta', CAST(N'1999-11-30' AS Date), N'Veteriner Diş Hekimi', 20000, CAST(N'2019-05-22' AS Date), N'albalta@gmail.com', N'05431246597')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (5, 3, N'Coşkun', N'Başar', CAST(N'1995-03-26' AS Date), N'Veteriner Beslenme Uzmanı', 21000, CAST(N'2014-11-10' AS Date), N'cobasar@gmail.com', N'05461237514')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (6, 3, N'Bensu', N'Belge', CAST(N'1996-07-17' AS Date), N'Veteriner Diş Hekimi', 20000, CAST(N'2016-08-25' AS Date), N'bebelge@gmail.com', N'05431267854')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (7, 5, N'Mehmet', N'Bural', CAST(N'1994-12-24' AS Date), N'Veteriner Hekim', 24000, CAST(N'2018-06-18' AS Date), N'mebural@gmail.com', N'05463219658')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (8, 5, N'Oğuzcan', N'Çağan', CAST(N'1998-11-09' AS Date), N'Veteriner Cerrah', 22000, CAST(N'2019-07-30' AS Date), N'ogcagan@gmail.com', N'05462158765')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (9, 2, N'Elif', N'Çark', CAST(N'1987-05-31' AS Date), N'Veteriner Hekim', 24000, CAST(N'2008-05-08' AS Date), N'elcark@gmail.com', N'05461784593')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (10, 1, N'Sena', N'Çelik', CAST(N'1989-07-16' AS Date), N'Veteriner Hekim', 24000, CAST(N'2014-04-10' AS Date), N'secelik@gmail.com', N'05436257890')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (11, 1, N'Gürbüz', N'Çuhadar', CAST(N'1992-03-10' AS Date), N'Veteriner Beslenme Uzmanı', 24000, CAST(N'2015-09-16' AS Date), N'gücuhadar@gmail.com', N'05461248752')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (12, 4, N'Ezgin', N'Davutoğlu', CAST(N'1985-08-22' AS Date), N'Veteriner Cerrah', 22000, CAST(N'2015-07-24' AS Date), N'ezdavut@gmail.com', N'05481246359')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (13, 4, N'Miraç', N'Dikbaş', CAST(N'1994-03-03' AS Date), N'Veteriner Diş Hekimi', 20000, CAST(N'2016-05-10' AS Date), N'midik@gmail.com', N'05497643120')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (14, 5, N'Firuze', N'Coşan', CAST(N'1992-07-24' AS Date), N'Veteriner Diş Hekimi', 21000, CAST(N'2017-09-17' AS Date), N'fircosan@gmail.com', N'05431254678')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (15, 2, N'Alya', N'Dur', CAST(N'1984-03-04' AS Date), N'Veteriner Cerrah', 22000, CAST(N'2008-10-24' AS Date), N'aldur@gmail.com', N'05431246597')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (16, 3, N'Bahar', N'Erkovan', CAST(N'1994-04-10' AS Date), N'Veteriner Cerrah', 22000, CAST(N'2014-06-02' AS Date), N'baher@gmail.com', N'05431246785')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (17, 4, N'Melike', N'Görür', CAST(N'1995-09-23' AS Date), N'Veteriner Beslenme Uzmanı', 21000, CAST(N'2015-09-12' AS Date), N'melgör@gmail.com', N'05491325467')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (18, 2, N'Katya', N'Kudu', CAST(N'1990-12-19' AS Date), N'Veteriner Beslenme Uzmanı', 21000, CAST(N'2016-05-05' AS Date), N'katdu@gmail.com', N'05462348752')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (19, 5, N'Hüseyin', N'Yıldız', CAST(N'1992-03-08' AS Date), N'Veteriner Beslenme Uzmanı', 21000, CAST(N'2013-09-09' AS Date), N'hüyıl@gmail.com', N'05432645785')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (20, 2, N'Zehra', N'Mengüç', CAST(N'1995-11-25' AS Date), N'Veteriner Diş Hekimi', 20000, CAST(N'2018-12-30' AS Date), N'zehmen@gmail.com', N'05461235203')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (21, 1, N'Barbaros', N'Mumcu', CAST(N'1980-12-07' AS Date), N'CEO', 50000, CAST(N'2010-01-09' AS Date), N'barbmum@gmail.com', N'05842134562')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (22, 3, N'Melike', N'Masır', CAST(N'1994-04-10' AS Date), N'Sekreter', 12000, CAST(N'2020-05-04' AS Date), N'memasır@gmail.com', N'05421326587')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (23, 4, N'Ülker', N'Oduncu', CAST(N'1993-06-17' AS Date), N'Sekreter', 12000, CAST(N'2023-06-03' AS Date), N'ülodun@gmail.com', N'05421023465')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (24, 5, N'İzel', N'Önen', CAST(N'1990-08-23' AS Date), N'Sekreter', 12000, CAST(N'2022-12-03' AS Date), N'izöne@gmail.com', N'05423120451')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (25, 1, N'Ebru', N'Özdel', CAST(N'1989-03-24' AS Date), N'Sekreter', 12000, CAST(N'2021-07-09' AS Date), N'eböz@gmail.com', N'05421325420')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (26, 2, N'İlay', N'Özgül', CAST(N'1999-11-30' AS Date), N'Sekreter', 12000, CAST(N'2020-06-05' AS Date), N'ilöz@gmail.com', N'05423164204')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (27, 4, N'Melis', N'Mezarcı', CAST(N'1995-09-23' AS Date), N'Patron', 26000, CAST(N'2015-08-05' AS Date), N'melmez@gmail.com', N'05431234562')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (28, 3, N'Anıl', N'Özdil', CAST(N'1990-12-01' AS Date), N'Patron', 26000, CAST(N'2014-05-09' AS Date), N'anöz@gmail.com', N'05531234513')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (29, 5, N'Merve', N'Özüberk', CAST(N'1999-05-08' AS Date), N'Patron', 26000, CAST(N'2013-02-03' AS Date), N'meröz@gmail.com', N'05632514852')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (30, 1, N'Zeynep', N'Poçan', CAST(N'1986-02-20' AS Date), N'Patron', 26000, CAST(N'2016-09-19' AS Date), N'zeypo@gmail.com', N'05632145784')
INSERT [dbo].[personel_bilgi] ([id], [klinikId], [ad], [soyad], [dogumTarihi], [unvan], [maas], [girisTarihi], [mail], [telNo]) VALUES (31, 2, N'Ayşe', N'Sar', CAST(N'1993-04-10' AS Date), N'Patron', 26000, CAST(N'2015-09-10' AS Date), N'aysar@gmail.com', N'05421234658')
SET IDENTITY_INSERT [dbo].[personel_bilgi] OFF
GO

# [dbo].[rel_urun]

In [0]:
SET IDENTITY_INSERT [dbo].[rel_urun] ON 
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (1, 3, 6, 0)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (2, 2, 7, 94)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (3, 5, 9, 57)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (4, 4, 20, 60)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (5, 4, 5, 31)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (6, 1, 8, 40)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (7, 1, 12, 100)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (8, 2, 13, 10)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (9, 4, 19, 50)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (10, 5, 21, 65)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (11, 2, 24, 30)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (12, 2, 23, 54)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (13, 3, 15, 10)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (14, 1, 13, 90)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (15, 3, 11, 20)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (16, 1, 27, 70)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (17, 2, 22, 400)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (18, 5, 26, 50)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (19, 4, 2, 60)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (20, 4, 3, 100)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (21, 1, 4, 0)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (22, 2, 25, 43)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (23, 3, 28, 32)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (24, 2, 14, 87)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (25, 1, 10, 79)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (26, 3, 16, 73)
INSERT [dbo].[rel_urun] ([id], [klinikId], [urunId], [urunAdet]) VALUES (27, 4, 17, 55)
SET IDENTITY_INSERT [dbo].[rel_urun] OFF
GO

# [dbo].[sahip_bilgi]

In [0]:
SET IDENTITY_INSERT [dbo].[sahip_bilgi] ON 
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (1, N'Aylin', N'Yılmaz', N'İstanbul, Beşiktaş Mahallesi, Barbaros Caddesi No:15', N'aylinyilmaz@gmail.com', N'05551234567')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (2, N'Kaan', N'Şahin', N'İzmir, Alsancak Mahallesi, Kıbrıs Şehitleri Caddesi No:23', N'kaansahin@gmail.com', N'05552345678')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (3, N'Elif', N'Çelik', N'Antalya, Lara Mahallesi, Kundu Caddesi No:7', N'elifcelik@gmail.com', N'05553456789')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (4, N'Barış', N'Kaya', N'Samsun, Atakum Mahallesi, Sahil Yolu No:45', N'bariskaya@gmail.com', N'05554567890')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (5, N'Zeynep', N'Aksoy', N'Ankara, Kızılay Mahallesi, Atatürk Bulvarı No:30', N'zeynepaksoy@gmail.com', N'05555678901')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (6, N'Emre', N'Demir', N'İstanbul, Kadıköy Mahallesi, Moda Caddesi No:12', N'emredemir@gmail.com', N'05556789012')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (7, N'Gizem', N'Öztürk', N'İzmir, Bornova Mahallesi, Ege Caddesi No:18', N'gizemozturk@gmail.com', N'05557890123')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (8, N'Caner', N'Arslan', N'Antalya, Konyaaltı Mahallesi, 100. Yıl Bulvarı No:5', N'canerarslan@gmail.com', N'05558901234')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (9, N'Melis', N'Gür', N'Samsun, İlkadım Mahallesi, Gazi Caddesi No:33', N'melisgur@gmail.com', N'05559012345')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (10, N'Berkay', N'Yıldız', N'Ankara, Bahçelievler Mahallesi, 7. Cadde No:21', N'berkayyildiz@gmail.com', N'05550123456')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (11, N'Aslıhan', N'Özdemir', N'İstanbul, Üsküdar Mahallesi, Bağlarbaşı Caddesi No:8', N'aslihanozdemir@gmail.com', N'05552345678')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (12, N'Burak', N'Topçu', N'İzmir, Karşıyaka Mahallesi, Mithatpaşa Caddesi No:16', N'buraktopcu@gmail.com', N'05553456789')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (13, N'Ceren', N'Korkmaz', N'Antalya, Muratpaşa Mahallesi, Çağlayan Bulvarı No:42', N'cerenkorkmaz@gmail.com', N'05554567890')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (14, N'Oğuzhan', N'Kılıç', N'Samsun, Atakum Mahallesi, Sahil Yolu No:28', N'oguzhankilic@gmail.com', N'05555678901')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (15, N'Selin', N'Demirci', N'Ankara, Çankaya Mahallesi, Tunalı Hilmi Caddesi No:11', N'selindemirci@gmail.com', N'05556789012')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (16, N'Tolga', N'Avcı', N'İstanbul, Beylikdüzü Mahallesi, Barış Bulvarı No:3', N'tolgaavci@gmail.com', N'05557890123')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (17, N'Ece', N'Koçak', N'İzmir, Gaziemir Mahallesi, Gazi Caddesi No:37', N'ecekokak@gmail.com', N'05558901234')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (18, N'Furkan', N'Akın', N'Antalya, Kepez Mahallesi, 5. Cadde No:14', N'furkanakin@gmail.com', N'05559012345')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (19, N'Dilara', N'Türk', N'Samsun, İlkadım Mahallesi, Cumhuriyet Caddesi No:25', N'dilaraturk@gmail.com', N'05550123456')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (20, N'Deniz', N'Yaman', N'Ankara, Etimesgut Mahallesi, Yıldırım Beyazıt Caddesi No:9', N'denizyaman@gmail.com', N'05552345678')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (21, N'Burcu', N'Şen', N'İstanbul, Şişli Mahallesi, Abide-i Hürriyet Caddesi No:36', N'burcusen@gmail.com', N'05553456789')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (22, N'Serkan', N'Gök', N'İzmir, Karabağlar Mahallesi, Adnan Menderes Bulvarı No:22', N'serkangok@gmail.com', N'05554567890')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (23, N'Seda', N'Aydın', N'Antalya, Lara Mahallesi, Fener Caddesi No:13', N'sedaaydin@gmail.com', N'05555678901')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (24, N'Onur', N'Yalçın', N'Samsun, Atakum Mahallesi, Atatürk Bulvarı No:17', N'onuryalcin@gmail.com', N'05556789012')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (25, N'Yasemin', N'Yıldırım', N'Ankara, Keçiören Mahallesi, 1. Cadde No:29', N'yaseminyildirim@gmail.com', N'05557890123')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (26, N'Hüseyin', N'Özbek', N'İstanbul, Ümraniye Mahallesi, Libadye Caddesi No:31', N'huseyinozbek@gmail.com', N'05558901234')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (27, N'Ayşe', N'Toprak', N'İzmir, Buca Mahallesi, Fevzi Çakmak Caddesi No:14', N'aysetoprak@gmail.com', N'05559012345')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (28, N'Emirhan', N'Yıldız', N'Antalya, Konyaaltı Mahallesi, Lara Caddesi No:5', N'emirhanyildiz@gmail.com', N'05550123456')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (29, N'Şeyma', N'Taşkın', N'Samsun, İlkadım Mahallesi, Gazi Caddesi No:20', N'seymataskin@gmail.com', N'05552345678')
INSERT [dbo].[sahip_bilgi] ([id], [ad], [soyad], [evAdresi], [mail], [telNo]) VALUES (30, N'Baran', N'Güneş', N'Ankara, Yenimahalle Mahallesi, Fatih Caddesi No:24', N'barangunes@gmail.com', N'05553456789')
SET IDENTITY_INSERT [dbo].[sahip_bilgi] OFF
GO

# [dbo].[tedarikci_bilgi]

In [0]:
SET IDENTITY_INSERT [dbo].[tedarikci_bilgi] ON 
INSERT [dbo].[tedarikci_bilgi] ([id], [ad], [konum], [mail], [telNo]) VALUES (1, N'Aslan Tıbbi Ürünler', N'İstanbul, Merkez Mahallesi, Ticaret Caddesi No:25', N'aslan_tıp_urunleri@info.com', N'5551790034')
INSERT [dbo].[tedarikci_bilgi] ([id], [ad], [konum], [mail], [telNo]) VALUES (2, N'Kaya Sağlık Ürünleri', N'Ankara, Kızılay Mahallesi, Sanayi Bulvarı No:18', N'kaya_saglik@info.com', N'5556310006')
INSERT [dbo].[tedarikci_bilgi] ([id], [ad], [konum], [mail], [telNo]) VALUES (3, N'Panda Oyuncakçılık', N'İzmir, Alsancak Mahallesi, Liman Caddesi No:10', N'panda_oyuncakcilik@info.com', N'5559810035')
INSERT [dbo].[tedarikci_bilgi] ([id], [ad], [konum], [mail], [telNo]) VALUES (4, N'Samsun Pet Mamaları', N'Samsun, Osmangazi Mahallesi, Organize Sanayi Bölgesi No:7', N'samsun_pet_mamalari@info.com', N'5554180016')
INSERT [dbo].[tedarikci_bilgi] ([id], [ad], [konum], [mail], [telNo]) VALUES (5, N'Antalya Pet Tekstil', N'Antalya, Muratpaşa Mahallesi, Turizm Bulvarı No:12', N'antalya_pet_tekstil@info.com', N'5551870007')
INSERT [dbo].[tedarikci_bilgi] ([id], [ad], [konum], [mail], [telNo]) VALUES (6, N'İstanbul Pet Gıda', N'İstanbul, Cumhuriyet Mahallesi, Bankalar Caddesi No:32', N'istanbul_pet_gida@info.com', N'5551870037')
INSERT [dbo].[tedarikci_bilgi] ([id], [ad], [konum], [mail], [telNo]) VALUES (7, N'Ankara Pet Ev Ürünleri', N'Ankara, Çankaya Mahallesi, Kurtuluş Caddesi No:30', N'ankara_pet_ev_urunleri@info.com', N'5559071006')
SET IDENTITY_INSERT [dbo].[tedarikci_bilgi] OFF
GO

# [dbo].[urun_bilgi]

In [0]:
SET IDENTITY_INSERT [dbo].[urun_bilgi] ON 
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (1, 1, 1, N'Saral Calm 5 Htp Sakinleştirici İlaç', 25.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (2, 2, 1, N'Reflex Yetişkin Tavuklu Renkli Kedi Maması', 35.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (3, 3, 1, N'Elastik Kedi Oyun Oltası', 10.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (4, 6, 1, N'Metapet Kedi Bit Karşıtı Şampuan', 15.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (5, 2, 2, N'Royal Canin Sterilised Kısırlaştırılmış Kedi Maması', 30.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (6, 3, 2, N'BioFeline Kedi Nanesi Oyun Topu', 12.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (7, 4, 2, N'MOLMEKS Köpek Yatağı', 45.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (8, 5, 2, N'hayystore Kedi Tırmalama Tahtası', 20.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (9, 6, 3, N'PetPlus Köpek Şampuanı', 18.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (10, 7, 3, N'FurryFriends Köpek Tüy Fırçası', 8.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (11, 8, 3, N'PawParadise Köpek Tasma', 14.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (12, 9, 3, N'CatComfort Kokulu Kedi Kumu', 22.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (13, 10, 4, N'VetCare Kulak Temizleme Sıvısı', 9.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (14, 11, 4, N'VetLibrary Köpek Eğitimi Kitabı', 27.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (15, 12, 4, N'CozyCats Yumuşak Kedi Yatağı', 34.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (16, 13, 4, N'TrainMaster Clicker Eğitim Aleti', 6.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (17, 14, 5, N'PetPorter Kedi Taşıma Çantası', 29.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (18, 15, 5, N'HealthGuard Köpek Sağlık Seti', 42.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (19, 1, 5, N'VetMed Köpek Antibiyotik', 19.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (20, 2, 5, N'HappyPaws Puppy Köpek Maması', 23.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (21, 14, 6, N'SoftCat Kedi Seyahat Çantası', 17.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (22, 15, 6, N'CheckUpMate Köpek Sağlık Kontrol Cihazı', 54.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (23, 1, 6, N'PetRx Kedi Antibiyotik', 21.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (24, 2, 6, N'NutriMax Senior Köpek Maması', 28.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (25, 1, 7, N'HealthGuard Kedi İdrar Yolu Enfeksiyonu İlaç', 32.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (26, 2, 7, N'ProVita Adult Köpek Maması', 38.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (27, 3, 7, N'PawJoy Köpek Kemik Oyuncak', 14.99)
INSERT [dbo].[urun_bilgi] ([id], [kategoriId], [tedarikId], [UrunAd], [urunFiyat]) VALUES (28, 6, 7, N'HappyPets Kedi Mantar Karşıtı Şampuan', 19.99)
SET IDENTITY_INSERT [dbo].[urun_bilgi] OFF
GO

# [dbo].[urun_fatura_bilgi]

In [0]:
SET IDENTITY_INSERT [dbo].[urun_fatura_bilgi] ON 
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (1, 2, N'Erna', N'Arikan', 140, N'Nakit', 300, CAST(N'2023-12-14' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (2, 3, N'Mustafa', N'Arif', 200, N'Nakit', 900, CAST(N'2023-04-19' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (3, 4, N'Ali', N'Balta', 210, N'Banka Havale', 1000, CAST(N'2023-06-10' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (4, 5, N'Coşkun', N'Başar', 180, N'Kredi Kartı', 400, CAST(N'2023-03-25' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (5, 6, N'Bensu', N'Belge', 190, N'Kredi Kartı', 900, CAST(N'2023-01-26' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (6, 7, N'Mehmet', N'Bural', 170, N'Banka Havale', 700, CAST(N'2023-11-19' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (7, 8, N'Oğuzcan', N'Çağan', 2300, N'Kredi Kartı', 300, CAST(N'2023-02-08' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (8, 9, N'Elif', N'Çark', 200, N'Kredi Kartı', 500, CAST(N'2023-10-13' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (9, 10, N'Sena', N'Çelik', 160, N'Nakit', 1200, CAST(N'2023-09-05' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (10, 11, N'Gürbüz', N'Çuhadar', 140, N'Nakit', 300, CAST(N'2023-03-06' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (11, 12, N'Ezgin', N'Davutoğlu', 180, N'Kredi Kartı', 900, CAST(N'2023-12-02' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (12, 13, N'Miraç', N'Dikbaş', 180, N'Kredi Kartı', 500, CAST(N'2023-02-23' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (13, 14, N'Firuze', N'Coşan', 210, N'Nakit', 600, CAST(N'2023-06-16' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (14, 15, N'Alya', N'Dur', 200, N'Banka Havale', 400, CAST(N'2023-01-08' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (15, 16, N'Bahar', N'Erkovan', 210, N'Kredi Kartı', 200, CAST(N'2022-12-12' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (16, 17, N'Melike', N'Görür', 240, N'Kredi Kartı', 500, CAST(N'2022-12-12' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (17, 18, N'Katya', N'Kudu', 190, N'Kredi Kartı', 1000, CAST(N'2022-08-09' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (18, 19, N'Zehra', N'Mengüç', 170, N'Kredi Kartı', 900, CAST(N'2022-10-25' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (19, 20, N'Barbaros', N'Mumcu', 180, N'Nakit', 800, CAST(N'2022-09-22' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (20, 21, N'Melike', N'Masır', 190, N'Banka Havale', 600, CAST(N'2022-04-16' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (21, 22, N'Ülker', N'Oduncu', 210, N'Banka Havale', 700, CAST(N'2022-07-10' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (22, 23, N'İzel', N'Önen', 180, N'Banka Havale', 1000, CAST(N'2022-09-13' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (23, 24, N'Ebru', N'Özdel', 190, N'Kredi Kartı', 300, CAST(N'2022-07-08' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (24, 25, N'İlay', N'Özgül', 200, N'Banka Havale', 500, CAST(N'2022-12-02' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (25, 26, N'Merve', N'Özüberk', 210, N'Nakit', 700, CAST(N'2022-09-03' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (26, 27, N'Zeynep', N'Poçan', 170, N'Nakit', 900, CAST(N'2022-01-06' AS Date))
INSERT [dbo].[urun_fatura_bilgi] ([id], [urunId], [ad], [soyad], [tutar], [odemeTuru], [topAdet], [kesimTarihi]) VALUES (27, 28, N'Ayşe', N'Sar', 180, N'Banka Havale', 600, CAST(N'2022-08-22' AS Date))
SET IDENTITY_INSERT [dbo].[urun_fatura_bilgi] OFF
GO

# [fk_hasta]

In [0]:
ALTER TABLE [dbo].[Asi_Test_Bilgileri]  WITH CHECK ADD  CONSTRAINT [fk_hasta] FOREIGN KEY([hastaId])
REFERENCES [dbo].[hasta_bilgi] ([id])
GO
ALTER TABLE [dbo].[Asi_Test_Bilgileri] CHECK CONSTRAINT [fk_hasta]
GO

# [FK__hasta_bil__sahip__412EB0B6]

In [0]:
ALTER TABLE [dbo].[hasta_bilgi]  WITH CHECK ADD FOREIGN KEY([sahipId])
REFERENCES [dbo].[sahip_bilgi] ([id])
GO

# [FK__hasta_bil__veter__4222D4EF]

In [0]:
ALTER TABLE [dbo].[hasta_bilgi]  WITH CHECK ADD FOREIGN KEY([veterinerId])
REFERENCES [dbo].[personel_bilgi] ([id])
GO

# [FK__hastalik___hasta__47DBAE45]

In [0]:
ALTER TABLE [dbo].[hastalik_gecmisi]  WITH CHECK ADD FOREIGN KEY([hastaId])
REFERENCES [dbo].[hasta_bilgi] ([id])
GO

# [FK__hizmet_bi__hasta__44FF419A]

In [0]:
ALTER TABLE [dbo].[hizmet_bilgi]  WITH CHECK ADD FOREIGN KEY([hastaId])
REFERENCES [dbo].[hasta_bilgi] ([id])
GO

# [FK__musteri_f__muste__3E52440B]

In [0]:
ALTER TABLE [dbo].[musteri_faturalari]  WITH CHECK ADD FOREIGN KEY([musteriId])
REFERENCES [dbo].[sahip_bilgi] ([id])
GO

# [FK__personel___klini__398D8EEE]

In [0]:
ALTER TABLE [dbo].[personel_bilgi]  WITH CHECK ADD FOREIGN KEY([klinikId])
REFERENCES [dbo].[klinik_bilgi] ([id])
GO

# [FK__rel_urun__klinik__5441852A]

In [0]:
ALTER TABLE [dbo].[rel_urun]  WITH CHECK ADD FOREIGN KEY([klinikId])
REFERENCES [dbo].[klinik_bilgi] ([id])
GO

# [FK__rel_urun__urunId__5535A963]

In [0]:
ALTER TABLE [dbo].[rel_urun]  WITH CHECK ADD FOREIGN KEY([urunId])
REFERENCES [dbo].[urun_bilgi] ([id])
GO

# [FK__urun_bilg__kateg__5070F446]

In [0]:
ALTER TABLE [dbo].[urun_bilgi]  WITH CHECK ADD FOREIGN KEY([kategoriId])
REFERENCES [dbo].[kategori] ([id])
GO

# [FK__urun_bilg__tedar__5165187F]

In [0]:
ALTER TABLE [dbo].[urun_bilgi]  WITH CHECK ADD FOREIGN KEY([tedarikId])
REFERENCES [dbo].[tedarikci_bilgi] ([id])
GO

# [FK__urun_fatu__urunI__5812160E]

In [0]:
ALTER TABLE [dbo].[urun_fatura_bilgi]  WITH CHECK ADD FOREIGN KEY([urunId])
REFERENCES [dbo].[urun_bilgi] ([id])
GO

# [veterinerdb]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [veterinerdb] SET  READ_WRITE 
GO